### ISSUE TITLE
how can we add our some special chars

### ISSUE THREAD

**Issue by adilsaeed31** [M1Sh0u/pGenerator#3]
Hi,
Nice plugin, you have can you please tell me how can i change special characters in it. like i want to add "@, ! *, #" in pgenerator password only as special chracter can i change that only when we generate password then password only contains above 3 special characters.

Urgent answer required, i'm struck at this time.

Thansk
Adil

**Comment by khundaqji** [comment]
Too late, but worths putting some data for others 

Use the following keys and their corresponding values as needed,

$('#secret-generator-button').pGenerator({
        'bind': 'click',
        'passwordElement': '#secret',
        'passwordLength': 16,
        'uppercase': true,
        'lowercase': true,
        'numbers':   true,
        'specialChars': true
    });

**Comment by jebr** [comment]
Just change the number to the one you wish in pGenerator.jquery.js
`special_chars_array = [33,35,37,42,63,64,94,95];`
Numbers can be found here [http://www.asciitable.com/](url)
