### ISSUE TITLE
JQuery V2

### ISSUE THREAD

**Issue by whenry** [M1Sh0u/pGenerator#4]
I get error TypeError: $(...).pGenerator is not a function when trying to use with JQuery v2.1.3, must be compatibility issue with JQ v2?

**Comment by M1Sh0u** [comment]
There might be an issue on your side. Please verify if the plugin has been correctly added in the page you need to be used.

I've verified the plugin with jQuery 2.1.3 and the it is working as it should: http://jsfiddle.net/rprjp1xw/1/
